server:
 port: 8000

spring:
 application:
  name: 'api-gateway'
  
eureka:
 instance:
  hostname: 'localhost'
 client:
  registerWithEureka: true
  fetchRegistry: false
  serviceUrl:
   defaultZone: 'http://localhost:9090/eureka/'
  server: 
   wait-time-in-ms-when-sync-empty: 3000
 
zuul:
 prefix: '/api'
 ignoredServices: '*'
 routes:
  orders:
   path: '/orders/**'
   serviceId: 'ORDER'
   stripPrefix: false
  accounts:
   path: '/accounts/**'
   serviceId: 'ACCOUNT'
   stripPrefix: false 
